version: '3.1'
services:
  mysql_db:
    image: mysql:8
    container_name: MySQL8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_USER: sys_temp
      MYSQL_PASSWORD: qwerty
    volumes:
      - /root/mysql/db-data:/var/lib/mysql/
      - /root/mysql/backup:/tmp/mysql/backup
